[package]
name = "LeNet_FromScratch"
version = "0.1.0"
edition = "2024"

[dependencies]
ndarray = { version = "0.17.2", features = ["approx"] }
csv = "1.4.0"
serde = { version = "1.0.228", features = ["derive"] }
rand = "0.10.0"
ndarray-rand = "0.16.0"
rand_chacha = "0.9.0"
rand_distr = "0.5.1"
float-cmp = "0.10.0"
approx = "0.5.1"
image = "0.25.10"
pipe = "0.4.0"